baseURL: "https://joelogs.com/"
title: JoeLogs
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Sathvik Joel
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  # ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  # ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "./resources/_gen/assets/shrimp_io/favicon.ico"
    # favicon16x16: "./resources/_gen/assets/shrimp_io/favicon-16x16.png"
    # favicon32x32: "./resources/_gen/assets/shrimp_io/favicon-32x32.png"
    # apple_touch_icon: "./resources/_gen/assets/shrimp_io/apple-touch-icon.png"
    # safari_pinned_tab: "./resources/_gen/assets/shrimp_io/favicon.ico"

  label:
    text: "Joe'Logs"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "\U0001F44B Welcome to Joe'Logs"
    Content: Hi, this is Joel. I'm documenting my learning notes in these blogs. I am a tech enthusiast, learning new things excites me :)

  socialIcons:
    - name: twitter
      url: "https://twitter.com/JoelSathvik"
    - name: linkedin
      url: "https://www.linkedin.com/in/sathvik-joel-97524b18b/"
    - name: github
      url: "https://github.com/SathvikJoel"
    - name: instagram
      url: "https://www.instagram.com/its.me.sathvik/"
    - name: spotify
      url: "https://open.spotify.com/user/2ur48kajlcusfrez1xv8mvhtv"


  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
taxonomies:
          category: categories
          tag: tags
          series: series
menu:
  main:
    - identifier: Posts
      name: Posts
      url: /
      weight: 1
    - identifier: Search
      name: Search
      url: /search/
      weight: 2
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 6
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
    - identifier: Series
      name: Series
      url: /series/
      weight: 4
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 3  

    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    guessSyntax: true
    # lineNos: true
    style: dark

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
